export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CHARITY_START = 'CHARITY_START';
export const CHARITY_HEALTH = 'CHARITY_HEALTH';
export const CHARITY_FEATURED = 'CHARITY_FEATURED';
export const CHARITY_FAIL = 'CHARITY_FAIL';
